### ISSUE TITLE
Constraint View Warning Icon disappearing upon selecting Constraint

### ISSUE THREAD

**Issue by Raixxor** [FeatureIDE/FeatureIDE#1039]
#### Prerequisitives
* **Eclipse Version:**  4.13
* **Git branch/Commit-ID:** release3.6 / ca634bc78ad35eb62f8ee7dc8a6586d4e1fbf01b

### Issue description
After selecting a Constraint in the Constraint View with a warning, the warning disappears until the Feature Model is focused again. 

![image](https://user-images.githubusercontent.com/25290815/82808595-90c92c00-9e8a-11ea-8793-882fb72d40a6.png)
---
---

![image](https://user-images.githubusercontent.com/25290815/82808642-a8a0b000-9e8a-11ea-885f-e9eca3b2cbf2.png)

**Comment by tthuem** [comment]
This is similar to what happens without the constraints view. As the highlighting is based on the current selection, a selection of a constraint below the diagram also results in a change of the highlighting.

In this case, it seems that we could keep the explanation highlighting as is. However, the question is what happens if the selected constraints itself induces another explanation being shown.

**Comment by h3ssto** [comment]
Related to #1028
