### ISSUE TITLE
No Undo and Redo for Feature Attributes View

### ISSUE THREAD

**Issue by Rahel12342** [FeatureIDE/FeatureIDE#1150]
#### Prerequisitives
* **Eclipse Version:**  `2020-03 (4.15.0))`
* **FeatureIDE-Version:**  `3.7`
* **Operating system:** `Windows 10`
* **Java runtime used to run eclipse:** `jdk-14.0.1`
* **FeatureIDE Composer:** `Extended Feature Modeling`

### Issue description
Feature Attributes View does not support Undo/Redo. Once an attribute was changed, there is no possibility to change it back except doing it manually (or quitting the editor without saving).

**Comment by tthuem** [comment]
Undo and redo can probably be enabled in a similar way as used for the constraints view (#1026).

**Comment by johannesherschel** [comment]
Enabling the undo/redo actions can indeed be done as for the constraints view. However, this issue requires some additional work, because the attribute actions themselves (add, edit, ...) have no undo/redo support, while the constraint actions supported undo/redo already.

**Comment by johannesherschel** [comment]
While working on this issue, I found a related bug: the value of a configurable attribute cannot be reset to empty in the attribute view of an extended configuration after it has been set to a non-empty value.
As I am changing the relevant code anyway, I will fix this bug along with this issue.

**Comment by johannesherschel** [comment]
Another bug: when changing the unit of a recursive attribute, occurrences at the child features are not updated in the attribute view immediately (both parent and child features must be selected in the feature model diagram so they are visible in the attribute view).

This will also be fixed with the changes to the attribute operations as part of this issue.
