### ISSUE TITLE
Multi-UVL: Renaming of imported features causes unexpected behaviour

### ISSUE THREAD

**Issue by michaelsoft-binbows** [FeatureIDE/FeatureIDE#1174]
#### Prerequisitives
* **Eclipse Version:**  `4.17`
* **FeatureIDE-Version:**  `3.7.1`
* **Operating system:** `Debian 11, KDE Plasma 5.20.5`
* **Java runtime used to run eclipse:** `jdk-14.0.1`
* **FeatureIDE Composer:** `Extended Feature Model`
* **Java compiler used to build the FeatureIDE plugin:** `1.8`

### UVL: Renaming of imported features causes expected behaviour

In UVL, external feature models can be imported. It is possible to rename a feature of an imported feature model. This causes to update the current feature model view only. The original feature model remains unaltered. After reopening the current feature model, the correct name is displayed as expected. In conclusion, the view changes only and the data remains unchanged. 

**Example**
In figure 1 you can see the imported feature model `os.OperationSystem`. `os.Windows` is an imported feature.

**Steps to reproduce**
1. Select an imported feature (blue coloured border feature).
2. Perform one left click on the selected feature.
3. Rename.
4. Hit enter.

![feature_issue8](https://user-images.githubusercontent.com/83942964/130253058-6ad4c677-ebf2-47e5-8066-f7a9304461dc.png)
Figure 1.

**Comment by Rahel12342** [comment]
There already exists a "isExternalFeature()" for a feature and "hasExternalFeature()" for a selection (multiple (?) selected features) in the class "AFeatureModelAction" that can be called when validating an Action. This way it is already forbidden in the context menu.

Comment to this issue: When renaming the feature (e.g., rename to os.notWindows) and saving, for me it does not change back. When reopening the model after closing, the source tab is opened, and trying to change back to the feature diagram is not possible with the notification "Invalid reference: feature os.notWindows does not exist". But since it is an imported feature, it is not listed in the file. Looking to the OperatingSystem model, the features name is still "Windows" (Maybe something that would change with issue #1134).

Anyway, I will simply forbid renaming the feature in any way.
