### ISSUE TITLE
Ubuntu: Configurable checkbox in Attributes view missing

### ISSUE THREAD

**Issue by cpwnd** [FeatureIDE/FeatureIDE#1324]
#### Prerequisitives
* **Eclipse Version:**  `eclipse.buildId=4.20.0.I20210611-1600` (I downloaded it today)
* **FeatureIDE-Version:**  `3.8.0`
* **Operating system:** `Ubuntu 18.04`
* **Java runtime used to run eclipse:** `openjdk 11.0.11 2021-04-20`

### Issue description
I'm in the feature model editor view with attributes view beneath it.

When I want to enable the "Configurable" checkbox of an attribute element in the feature attribute view, there is no checkbox (also no checkbox for recursive). The table cells are empty.

**Comment by SundermannC** [comment]
This issue seems to be caused by the new Eclipse version(s). The following workaround seems to work.
1. Open the Feature Attributes View
2. Change the Theme in Window -> Preferences -> Appearance
3. The checkboxes should now be visible until restarting Eclipse or the attributes view is closed.

Nevertheless, this workaround is rather inconvenient and we should continue to look for another solution.

**Comment by SundermannC** [comment]
As this issue seems to persist with the CheckBox widget under ubuntu, we decided to replace it with a dropdown widget for now.

**Comment by skrieter** [comment]
Fixed
