### ISSUE TITLE
Check whether the cheat sheet is consistent with FeatureIDE's functionality

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#154]
Make sure that all functionality is documented and that all is consistent with the current UI

**Comment by tthuem** [comment]
As the functionality is also documented in the wiki, you may report inconsistencies/missing functionality in the wiki in a separate issue.

**Comment by tthuem** [comment]
Seems to be a larger project. Marcus, what about moving it to next milestone?

**Comment by pinnecke** [comment]
Working on both, the cheat sheet and the wiki, could lead to redundant work. What's about shrinking the cheat sheet to a *please look at the wiki* page? If you want to provide an easy *getting started*, why not putting this into the wiki? Another benefit is that we could embed *video* material, showing how to e.g. create a new project, where Feature IDE stores files etc. I personally prefer short video introductions rather than the current text presentation (at least for a very quick *getting started* with UI and handling). I suggest to discuss this in short in the next meeting.

**Comment by tthuem** [comment]
There was quite some effort involved to come up with the cheat sheet and, thus, I would not like to see that we do not have one anymore. We should discuss in the next meeting how to avoid redundant effort here.

**Comment by pinnecke** [comment]
As far as I can see, the cheat sheet is consistent with the current version (expect some minor changes, like "FeatureIDE File" to "FeatureIDE Source File" and so on. I found some strange redundant text and wrong text placement. To organize the cheat sheet in a more consistent way, I create a (wiki page)[https://github.com/tthuem/FeatureIDE/wiki/Tutorial-Start] which is more or less a copy&paste of the entire cheat sheet but cleaned up and order a slight better (and with images!). This was necessary because the inside-Eclipse-cheat-sheet-Editor is not well designed enough for fast text changes and a bit buggy to my mind. However, I will move and improve the text and copy it back to cheat sheet when I've finished.

**Comment by pinnecke** [comment]
Please comment. What are the next steps?

**Comment by tthuem** [comment]
We should discuss this in the next meeting.

**Comment by tthuem** [comment]
@pinnecke Sorry, did not notice that you are waiting for my input. We have indeed to many issues. :) Please go ahead and update the cheat sheet to the current state of the wiki. If there is not much time, just focus on main flaws and close the issue afterwards.

**Comment by pinnecke** [comment]
Cheat sheet seems consistent with current UI. As already stated, the eclipse cheat sheet strategy is a bit hard from a usability perspective, and should be replaced by a link to a website containing a video tutorial. However, current state seems fine.
