### ISSUE TITLE
New algorithm for calculating indeterminate hidden features

### ISSUE THREAD

**Issue by fbenduhn** [FeatureIDE/FeatureIDE#25]
The selection of the feature beatiful is implied by the selection of the feature wonderful.
The behavior of the configuration editor works well. 

Attachment:
https://faracvs.cs.uni-magdeburg.de/projects/tthuem-FeatureIDE/attachment/ticket/447/model.xml

**Comment by tthuem** [comment]
Link does not work anymore, description is unclear.

**Comment by tthuem** [comment]
Restored the file content:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
	<featureModel chosenLayoutAlgorithm="1">
		<struct>
			<and abstract="true" mandatory="true" name="HelloWorld">
				<feature name="Hello"/>
				<alt abstract="true" name="Feature">
					<feature hidden="true" mandatory="true" name="Beautiful"/>
					<feature mandatory="true" name="Wonderful"/>
				</alt>
				<feature name="World"/>
			</and>
		</struct>
		<constraints/>
		<comments/>
		<featureOrder userDefined="false"/>
	</featureModel>
```

**Comment by tthuem** [comment]
Could you please provide some details on what is solved exactly? As this was planned as a master's thesis, it is unlikely that you fixed it with a single comit. ;)

**Comment by skrieter** [comment]
### I implemented the following analysis:
- Get CNF of feature model
- For each hidden feature f_i:
  - CNF2 <- Slice all hidden features but f_i from CNF
  - CNF3 <- Remove f_i from all clauses of CNF2 (not slicing, simply remove)
  - If CNF3 is satisfiable, the f_i is indeterminate
	
### The idea behind it is the following:
**Assumption:** 
Let C = {c_1, ..., c_n} be the formula in CNF with c_i the single clauses and f_i the only hidden feature in C.

**I.**
- Now, let:
C_true be the formula that is created by replacing all occurrences of f_i in C with true,
C_false be the formula that is created by replacing all occurrences of f_i in C with false, and
C_combined = C_true and C_false

**II.**
- Iff f_i is indetermined, there is at least one satisfiable configuration in which we defined all non-hidden features and it is still possible to freely choose a value for f_i.
|= Iff f_i is determined, there is no satisfiable configuration in which we defined all non-hidden features and it is still possible to freely choose a value for f_i.
|= Iff f_i is determined, C_true and C_false should have disjunct solution spaces.
|= Iff f_i is determined, C_combined is unsatisfiable
|= Iff f_i is indetermined, C_combined is satisfiable
	
**III.**
- We can split the clauses from C in three groups:
C_non = clauses that don't contain f_i
C_pos = clauses that contain positive f_i
C_neg = clauses that contain negative

- In C_true:
 All clauses of C_pos would be satisfied (thus can be removed completely),
From all clauses of C_neg we can remove -f_i, as it can not be (the result C'_neg)
C_non would be unaffected
		
- In C_false:
All clauses of C_neg would be satisfied (thus can be removed completely),
From all clauses of C_pos we can remove -f_i, as it can not be (the result C'_pos)
C_non would be unaffected

- C_combined = C_true and C_false
|= C_combined = (C_non and C'_neg) and (C_non and C'_pos)
|= C_combined = C_non and C'_neg and C'_pos
|= C_combined = C with all occurrences of f_i removed

**IV.**
- From **II** and **III**:
|= Iff C with all occurrences of f_i removed is satisfiable, then f_i is indetermined
	
### For the implementation:
- Slicing is necessary as our assumption is that f_i is the ONLY hidden feature.
Otherwise the other hidden feature might interfere with the analysis (i.e., cause an unwanted contradiction).
- Currently the slicing should be the most time-consuming task, it might be avoidable, but at the moment I don't know how

**Comment by tthuem** [comment]
Great! I guess there is no need for a thesis anymore, but sounds like a paper worth to be published. For instance, we could check which of the Linux features are indeterminate. I think this has been done somehow already, but with an exhaustive analysis enumerating all valid configurations of parts of the feature model.

Sounds like a similar analysis could be used to check whether a certain feature in the feature model does have no influence on the mapping (i.e., #ifdef annotations).
