### ISSUE TITLE
Dialog New -> FeatureIDE Source File not displayed

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#256]
I have a problem with my little FeatureIDE project. I can't create Source Files through the FeatureIDE perspective. When I click: New -> FeatureIDE Source File nothing happend. No dialog shows up.
You can test it with this project under:
https://github.com/TUBS-ISF/spl2015.christopher.sontag/tree/master/Christopher-Sontag-Task1

Version used: 
FeatureIDE 2.7.3.201503021756
Eclipse Luna SR2 (4.4.2)

FeatureIDE downloaded from official site at http://wwwiti.cs.uni-magdeburg.de/iti_db/research/featureide/
Thanks,
Christopher

**Comment by skrieter** [comment]
You are using a feature modeling project. These projects are for modeling purposes only and are not intended to have source files, therefore the dialog is disabled.
(Sorry for the confusion, we will add a warning or disable the button in future versions)

If you use a FeatureIDE-Project with a "real" composer (e.g., FeatureHouse), you will be able to create source files via the dialog.

_(Note, that your model will be invalid for other composers, since some feature names contain whitespaces and special characters)_

**Comment by tthuem** [comment]
We should display a warning instead of doing nothing. I'm also fine with disabling the action and adding a tool tip describing why it is deactivated.

**Comment by tthuem** [comment]
Disabling the menu should be rather easy.

@pinnecke Can you have a look at it? (Before we continue to move it to the next milestone again.)

**Comment by Kogoro** [comment]
I tried the feature modeling composer with the latest nightly build and it still exists. The difference is that the window will open, but you can't "Finish" the progress because the language box is empty.

**Comment by Kogoro** [comment]
Now the language box will be only available with more than two languages. Also, when there is no language available, e.g. with the feature modeling composer, an error message "Source files not allowed with this composer" will be shown.

**Comment by tthuem** [comment]
Jens, can you do the review?

**Comment by meinicke** [comment]
commit look reasonable.

**Comment by tthuem** [comment]
Christopher, please go ahead and merge it.
