### ISSUE TITLE
Inheritance with Velvet Changes Semantics of Input Model

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#282]
Created an XML feature model with an or group, which is transformed into mandatory features for inheritance when combining it with instances:

![zwischenablage-1](https://cloud.githubusercontent.com/assets/5330357/8570244/5a418706-257f-11e5-98eb-92ee1b0088ca.png)

**Comment by tthuem** [comment]
@skrieter Still sounds like a no-go, as this can lead to weird results. Is this already fixed? What is the problem here?

**Comment by tthuem** [comment]
Christopher, no need to reproduce it anymore.

**Comment by RSchroeter** [comment]
Yes, it is an error. The original solution for this case was an or-group with three features. I will fix this issue with the original solution. However, I don't like this solution anymore because it is too restrictive (i.e., for an alternative group). We should discuss about this scenario in an additional meeting...
