### ISSUE TITLE
Constraint falsely marked as redundant

### ISSUE THREAD

**Issue by AlexanderKnueppel** [FeatureIDE/FeatureIDE#347]
#### Prerequisitives
* **Eclipse Version:**  `4.4.2`
* **FeatureIDE-Version:**  `2.7.5`
* **Operating system:** `Windows 7/10`
* **Java runtime used to run eclipse:** `1.8.0`
* **FeatureIDE Composer:** ``
* **Git branch/Commit-ID:**  `f67728363a22a4619b06c9624a4624afb1dfbd58`
* **Java compiler used to build the FeatureIDE plugin:** ``

### Issue description
In the feature model below, the constraint *A_1 => A* is marked as redundant. This feature model omits the product {C}, as *A_1* or *B_1* needs to be selected which leads to either feature *A* or *B* in the end product.

![image](https://cloud.githubusercontent.com/assets/263321/14894712/46c71e82-0d75-11e6-9ebd-7a9277ab4df1.png)

If I remove this constraint, the following result appears:

![image](https://cloud.githubusercontent.com/assets/263321/14894824/d0c9f898-0d75-11e6-83bb-252fa72502c4.png)

Now, the product {C} can be generated by selecting the abstract features *A_1* and *C_2*. Hence, this constraint shouldn't be marked as redundant?

**Comment by tthuem** [comment]
@SofiaAnanieva Do you agree that there is something wrong with the computation of redundant constraints? Any idea what is wrong? The wrong computation could also harm some of your explanations.

**Comment by SofiaAnanieva** [comment]
@tthuem Thanks for pointing that out.

Yes, I agree with you. The constraint shouldn’t be marked as redundant in the first place. 
I rebuild the feature model and our BCP algorithm doesn’t generate an explanation for this falsely marked constraint, which is actually the correct behavior. 

I debugged the error. There are at least two things which are conspicious:

1)	All abstract features are set to null after calling method _calculateReplacingMap()_ inside method _compare()_ in class **ModelComparator**
2)	This seems to be propagated. The method _implies()_ requires the old model (without the new constraint to analyze) and the new model (with the new constraint to analyze) in order to check if both models imply each other. If yes, the constraint is redundant. However, the model to be implied is always NULL. IF the implied model is null, _implies()_ always returns true which results in the constraint to be interpreted as redundant.

One solution lies in commenting out the code in method _implies()_ which returns true if the implied model is NULL. Unfortunately, there is no commenting at all.

Apart from that, maybe there is something wrong with the handling of abstract features.

**Comment by tthuem** [comment]
@SofiaAnanieva As there are numerous issues related to that, it would be good if we could meet and you explain to me possible solutions.
