### ISSUE TITLE
FAMA exporter uses deprecated infrastructure

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#371]
Due to recent refactorings, FAMA export works, but relies on deprecated methods. Sebastian Krieter can provide more details if necessary.

**Comment by AlexanderKnueppel** [comment]
Seems to be the case for almost all exporters (and importers), as they use `AbstractFeatureModelWriter` (`AbstractFeatureModelReader`, respectively), which is depricated. 

What is the correct approach for an exporter? Are there any examples yet?

**Comment by skrieter** [comment]
Hi,
Import and export for a certain format is now handled in one class, which implements the `IPersistentFormat` interface.

I already changed the interface for all exporters (except FAMA) in the branch [Core_Lib](https://github.com/FeatureIDE/FeatureIDE/tree/Core_Lib).
You can just look there.
_Currently, the branch is unstable due to some dependency problems.
So if you want to execute the code, I recommend that you check out the `pre_lib_refactoring` tag within the branch._

**Comment by tthuem** [comment]
Sebastian, it does not seem useful to work on this while your branch is not integrated. Please let Alex know, once this is done.
