### ISSUE TITLE
.<feature-model-file>.xml files are created

### ISSUE THREAD

**Issue by anb0s** [FeatureIDE/FeatureIDE#376]
After updating to FeatureIDE 3.x new files are created automatically if one open a feature model:

![image](https://cloud.githubusercontent.com/assets/95811/16988485/d93af836-4e90-11e6-82e7-ee59c2083ead.png)

Are the files needed to work properly with FeatureIDE or just for debugging?
- If "Yes" we need a possibility to configure folder for them.
- If "No" we need an option to disable this behavior.

**Comment by skrieter** [comment]
The files are used to save meta information of the feature model (e.g. UI-Information for the feature diagram).
Currently it is not possible to change the folder.
That is why at moment it is hidden and has a very generic name.

The currently saved meta information are not required for the feature model to work with FeatureIDE unless the manual layout is used.

**Comment by tthuem** [comment]
@anb0s The idea of hidden files that you should not need to change the path. That's also used by Java projects and so on. Please tell us more why you think you need to specify a path for those files, if this is still an issue. For now, I'll close the issue.

**Comment by anb0s** [comment]
Yes it's OK, but in Eclipse all other plugins are using the folder ".settings" for this task. It would be better to have the same in FeatureIDE. We want to specify the path, because all files and folders created by used tools should "avoid polluting the root of the project"! Additionally it's easier for source versioning (ignore files) etc. to support only few known "hidden" folders inside or outside of source control.

**Comment by tthuem** [comment]
@anb0s Thanks for the input.

@skrieter Sounds like storing the file under .settings could be a good idea. What are your thoughts

**Comment by tthuem** [comment]
@anb0s Hi Andre, we discussed this issue again.

First, the ".settings" folder is typically used for settings to the project and not for particular files. Hence, we would not like to store the files with graphical properties there.

Second, as you can choose the path of the feature model, you can indirectly already configure the path to those files. The reason is that they are stored relative to the respective model file. Is it an option to use another path for the model files? Otherwise, we could store all those files in a special folder in the project root (e.g., ".featureide/path-to-file").

**Comment by anb0s** [comment]
Hello,

we have a model.xml file located in project root, because it worked in 2.x like this only. I think it changed or i just not tried to move it later. So i will move the model.xml to a subfolder and expect then that such file are created in this subfolder then only?

BTW. i do not see any options about the model location, only for configurations:
![image](https://cloud.githubusercontent.com/assets/95811/22333359/1de6e8ac-e3d6-11e6-96f7-5cd0681d4a29.png)
