### ISSUE TITLE
Moving constraints in manual layout does not work

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#407]
Switched to manual layout to move constraints for a more compact representation. However, moving features in manual layout only seems to reorder them (seen in the outline), which is intended with automatic layout only.

![zwischenablage-2](https://cloud.githubusercontent.com/assets/5330357/18342420/138155a4-75af-11e6-81a8-0966b90ca610.png)

Also, using the action to automatically layout constraints in manual layout has a different positioning as in automatic layout, which is confusing and could indicate code clones in our implementation of constraint layouting.

![zwischenablage-3](https://cloud.githubusercontent.com/assets/5330357/18342417/0fe07d6c-75af-11e6-977a-79bb6a609104.png)

**Comment by Subaro** [comment]
The issue is solved and I changed some more layout things:

### Before:

<img width="521" alt="aaa" src="https://user-images.githubusercontent.com/6231523/28818424-65442cc4-76ab-11e7-9155-5857834562a8.PNG">

### After:

<img width="294" alt="aaa2" src="https://user-images.githubusercontent.com/6231523/28818431-6ad37898-76ab-11e7-984f-8a48361efa53.PNG">
