### ISSUE TITLE
Revise and Merge new Collapsing and Shortcut Features (Team 1)

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#435]
Let us use this issue to discuss what changes are necessary prior to merge and to wrap up open issues afterwards.

![cam00001](https://cloud.githubusercontent.com/assets/5330357/19510371/377d266e-95e3-11e6-8a24-dfe4a0a42d6c.jpg)
![cam00002](https://cloud.githubusercontent.com/assets/5330357/19510373/3a60b1ca-95e3-11e6-9ab2-6dff5a722ec3.jpg)
![cam00003](https://cloud.githubusercontent.com/assets/5330357/19510377/3c916638-95e3-11e6-884b-70e04ab5275e.jpg)

**Comment by tthuem** [comment]
Are these open issues 19, 24 and 25 still valid?

**Comment by Subaro** [comment]
@tthuem 
Issue 19:
That is quite hard to make because the current FeatureModelDiagramEditor was created using an own event system. Now in the event system, the edit parts are triggered manually and on the other hand, there is code that was implemented on gefs command and request system. That code automatically refreshed the necessary edit parts. Sometimes the refresh is called twice or more times. Also, some methods should be split up in parts methods to have better control over the visual refresh. Because sometimes the event A does a refresh at the end. Before the refresh, it calls another event B that also calls a complete refresh. So I think it should be an own enchantment.

Issue 25:
Is already working again.

Issue 24:
At the moment not implemented because we didn't found the right method to resize the viewport. It's not necessary but could be useful for collapsing large feature models. We could maybe implement it afterward.

**Comment by Subaro** [comment]
I merged bs_team1 with explanation into develop

**Comment by tthuem** [comment]
Thanks for clarification. Does not sound like we can investigate both for a team/software project. Feel free to create separate issues, if necessary.
