### ISSUE TITLE
Revise and Merge new Configuration Map and Improved Color Handling (Team 3)

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#437]
Let us use this issue to discuss what changes are necessary prior to merge and to wrap up open issues afterwards.

![cam00008](https://cloud.githubusercontent.com/assets/5330357/19510617/4b87f674-95e4-11e6-8d43-3683b194e4ae.jpg)
![cam00009](https://cloud.githubusercontent.com/assets/5330357/19510619/4d368c7e-95e4-11e6-9dc4-e2574e6c509f.jpg)
![cam00010](https://cloud.githubusercontent.com/assets/5330357/19510621/4efb3ad2-95e4-11e6-93e0-5edf46731af7.jpg)

**Comment by tthuem** [comment]
Joshua, please summarize what is left to be done from those story cards and experience with your tests.

**Comment by Subaro** [comment]
At all, there were some small and big bugs I already fixed. Mostly about the Configuration Map. Now to the other Story Cards:

The Story Card 10 is about highlighting unused and false-optional features in the Configuration Map. But they are not. Is it because of the filter that they were removed? Because there are filters for unused and false-optional features.

Story Card 7 is not possible. Because you can´t extend the navigatorContent for the PackageExplorer. I think that this is the reason that the Project Explorer was created. The Project Explorer can do the same as the Package Explorer, but its's content is extended by the color functions.

Story Card 8 seems possible. I looked inside the LabelContenProvieder of the Project Explorer.  We should create a separate issue for the story card because it's quite some work.

Story Card 16 Most of them are synced. Some views not but they got a refresh button. (Configuration Map and Collaboration Diagram)

Story Card 17 I'm currently looking for the right way to implement this.

Story Card 18 I need to speak with @Kogoro about this. I not sure if that is going to work.

**Comment by Subaro** [comment]
Story Card 16 & 18 are now implemented and merged.

**Comment by tthuem** [comment]
Thanks!

SC 10: Yes, filter is sufficient.

SC 7: We had two groups of students that told us it is impossible. If you find a solution that would be great.

SC 8: Please go ahead. Sounds like something for the next team project (select the according milestone).

SC 16 + 18: Nice!

SC 17: New issue?

@Subaro Please close this issue when you created new issues and merged everything into develop.

**Comment by Subaro** [comment]
SC 17 is now implemented and merged.

**Comment by tthuem** [comment]
Sounds like we are done here. Thanks for your effort!
