### ISSUE TITLE
Add description to legend when graphical explanation uses two different colors.

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#459]
Sometimes the graphical explanation uses two different colors and the user don´t know what they mean.

We should add a description to the legend if that case happens.

**Comment by tthuem** [comment]
The color indicates in how many explanations is involved. Red means in all an black in none. Hence, red ones are more relevant to fix the anomaly.

Any ideas where such a description?

**Comment by tthuem** [comment]
In the feature diagram legend we could add one entry and add a tooltip to it. But that does not help for printouts. Two entries in the legend? One with the closest color to red and one with the closest to black (but not black)? But then, only appearing colors make sense. What happens if there is just one color?

**Comment by Subaro** [comment]
Thats the first attempt and I want some feedback.

Should I make two bars or only the one? If we make two bars the legend will be very long because we need to put one above the other one. So i created only one. 

![unbenannt](https://cloud.githubusercontent.com/assets/6231523/21896814/e816df1e-d8e7-11e6-9dcf-b602d7e377fe.PNG)

**Comment by FeatureIDE** [comment]
Looks quite good. There is only some context missing. Maybe we could generate a text above the bar like this: "Feature A96 false-optional because of highlighted dependencies: likely cause ... unlikely cause

BTW: The Collapsed icon is too large for the available space. What about removing "n" and giving it the same dimensions as all other entries?

**Comment by tthuem** [comment]
Looks quite good. There is only some context missing. Maybe we could generate a text above the bar like this: "Feature A96 false-optional because of highlighted dependencies: likely cause ... unlikely cause

BTW: The Collapsed icon is too large for the available space. What about removing "n" and giving it the same dimensions as all other entries?

**Comment by Subaro** [comment]
It now looks like this. 

<img width="833" alt="unbenannt" src="https://cloud.githubusercontent.com/assets/6231523/21928149/6f42c01a-d989-11e6-8f9f-12c44c600b83.PNG">

The Problem are the constraints. Should I display the complete constraints like:

<img width="950" alt="unbenannt2" src="https://cloud.githubusercontent.com/assets/6231523/21928421/fd6b2002-d98a-11e6-96c8-efca0484255a.PNG">

Or should I only display the defect and show the complete constraint in the tooltip?

<img width="676" alt="unbenannt3" src="https://cloud.githubusercontent.com/assets/6231523/21928554/c1f51130-d98b-11e6-8d0d-9190791c5f96.PNG">

**Comment by tthuem** [comment]
1. Collapsed icon still has other size than e.g. concrete
2. remove "the" from legend and tooltips
3. What about "1. constraint redundant because of ..."?
4. Is it possible to have the bar in the same width as the text above?

**Comment by Subaro** [comment]
1. is now the same size

2. done

3.  done. I'm counting only the current visible constraints.  

4. done

I finished the  entry now.

<img width="606" alt="unbenannt" src="https://cloud.githubusercontent.com/assets/6231523/22176259/ab742d0c-e006-11e6-8fe0-ea7731e3ba55.PNG">
