### ISSUE TITLE
Unnecessary entries in the legend of feature diagrams

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#484]
The explanation is not highlighting the cause of a void feature model. But the red colorization of the causing constraint was also removed. Now it is not so easy to find the constraint causing the void model. It´s only possible by iteration through the tooltips.

![aaaaaaa](https://cloud.githubusercontent.com/assets/6231523/24520688/a3966f6a-1589-11e7-953a-39fe52fabd16.JPG)

Also, there is still an entry in the legend for the red color of constraints.

**Comment by tthuem** [comment]
Indeed, the entry in the legend is not needed anymore and should be removed for the next version. @Subaro Can you take care of it?

Explanations should be shown now when hovering over any feature in the feature diagram. Does that work as expected?

Similar behavior should be available for false-optional and dead features (no constraint highlighted, no legend entry for constraints, explanation when hovering over feature).

**Comment by tthuem** [comment]
That's a corner case we haven't though of. In general, a feature model will be void because of several tree and cross-tree constraints. Indeed, if a cross-tree constraint itself is a contradiction, we could stay with an entry in the legend and highlighting. In summary:

1. Yes, but only if it is a contradiction by itself (without the rest of the feature model).

2. We should have an explanation for void feature models. The internal computation is essentially the same as for dead features; if the feature model is void, all features are dead and you basically have to compute the explanation for any feature (e.g., the root).

@Subaro Can you fix 1.?

@TimoGuenther Can you fix 2.?

**Comment by tthuem** [comment]
3. I also just noticed that there is no legend entry for void feature model.

@Subaro Can you fix 3.?

**Comment by TimoGuenther** [comment]
Explaining void features models works by interpreting the root feature as a dead feature. When an explanation for a feature is requested by selecting it, the feature status of the feature (`feature.getProperty().getFeatureStatus()`) is checked in `FeatureModelAnalyzer#addExplanation(IFeatureModelElement)` to decide which kind of explanation to generate. Unfortunately, the feature status in case of a void feature model is always set to `NORMAL` instead of `DEAD`, so no explanation is generated. This is because `FeatureModelAnalysis` fails to store the right result by marking the feature status as `DEAD`. This is in turn because the feature status is only updated when `FeatureModelAnalysis#valid` is `true` during `FeatureModelAnalysis#updateFeatures()` (meaning the feature model is satisfiable, meaning it is not void). In conclusion, the feature status needs to be updated properly even if the feature model is void. This is now done as of 3864ea5a9ec1652f38fa8873184d3b064779db6a.

I did not look at the implementation of how all features of a void feature model were shown as dead before, but considering setting the feature status is the semantically correct way, I suggest undoing the previous code changes used to accomplish this effect in order to avoid confusion.

Additionally, I noticed the legend explanation is updated using a static attribute `FeatureUIHelper#currentExplanation`. Besides being redundant in the first place, the fact that it is static might cause trouble with multiple editor instances. This could be avoided by getting the active explanation directly from `FeatureDiagramEditor` or by forwarding the `ACTIVE_EXPLANATION_CHANGED` event from `FeatureDiagramEditor` to the legend.

**Comment by tthuem** [comment]
@TimoGuenther Could you join our FeatureIDE meeting tomorrow 3pm? (So basically come 30 min earlier than our planned meeting?) That would simplify clarification.

**Comment by Subaro** [comment]
Like @TimoGuenther said I reversed a little bit and used the feature status now. I also removed the static attribute. 

@tthuem For unsatisfiable constraints, I also removed the legend entry because every unsatisfiable constraint makes the model void. That will be shown by the explanation that is now displaying correctly the cause of a void model. 

![unbenannt](https://cloud.githubusercontent.com/assets/6231523/24671416/b16734d0-1971-11e7-9055-7113e9a28315.JPG)


The legend entry for void feature model is still WIP.

**Comment by tthuem** [comment]
Sounds great!

**Comment by tthuem** [comment]
@TimoGuenther Is your recent commit for the current release? I'm asking as it is commited in develop right now.

**Comment by TimoGuenther** [comment]
I'll be there for the FeatureIDE meeting.

As for the commit branch, it's not a change specific to explanations, whereas all features of a void feature model were shown as dead on the development branch already, so that's the one I chose to commit to. Not sure what that means in terms of the release schedule.

**Comment by TimoGuenther** [comment]
As elaborated in 3864ea5a9ec1652f38fa8873184d3b064779db6a, tagging the status of every feature as dead when the feature model is void is actually not the semantically correct way. A different approach is taken in a03573a0b3823c96f74fe2b8644482d268da1d40.

**Comment by tthuem** [comment]
So you are ready for the legend to be updated by Joshua?

**Comment by TimoGuenther** [comment]
Yes. The graphical explanations for void feature models are now showing up again on the explanations branch.

**Comment by tthuem** [comment]
@Subaro When are you going to finish the legend?

**Comment by Subaro** [comment]
@tthuem The Legend Entry is ready but we found a problem when the legend. To move the legend currently a static reference is used. That leads to strange behaviors when opening a second instance of the FeatureModelEditor.

By example: Hiding the Legend in instance A and then refreshing the legend in instance B leads to a disapearing legend in instance B.

**Comment by tthuem** [comment]
I would prefer if you create a separate issue on that and merge the current fix. Then, I would create the new version.

**Comment by Subaro** [comment]
@tthuem It´s now pushed on release

**Comment by tthuem** [comment]
The text in the legend for void feature models is still non-sense:

![void](https://user-images.githubusercontent.com/5330357/34416971-57fde9f4-ebf6-11e7-9255-450b3ac7799f.png)

It should be "Feature model is void" instead.

**Comment by Subaro** [comment]
@tthuem The part where we changed the "Constraint makes the feature model void" was changed to "Feature model is void" was done as part of the team project 2 post changes. Which is still currently only on develop. 

I just created a small hotfix for the release. 

### Result

<img width="1075" alt="unbenannt" src="https://user-images.githubusercontent.com/6231523/34557933-42b9be56-f13c-11e7-8bf9-1b23e67b0d09.PNG">
