### ISSUE TITLE
Graphical void explanation is not displayed in some cases.

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#525]
#### Prerequisitives
* **Eclipse Version:**  `Neon.3`
* **FeatureIDE-Version:**  `3.3 with Nightly Update`
* **Operating system:** `Windows 10`
* **Java runtime used to run eclipse:** `1.7`

### Issue description
There is no graphical explanation for the given feature model with constraints 
![unbenannt](https://cloud.githubusercontent.com/assets/6231523/25288287/24063468-26c5-11e7-907d-ac4728821044.PNG)

The graphical explanation is displayed for the same feature model with some different constraints 
![unbenannt](https://cloud.githubusercontent.com/assets/6231523/25288353/55918744-26c5-11e7-907e-40eacc38d4fd.PNG)

**Comment by TimoGuenther** [comment]
The BCP algorithm derives `Behavior` and then `Modes` to be true since they are mandatory children. Unfortunately, at that point there are no unit-open clauses left. It would have to guess an assignment and potentially backtrack to find an explanation, which is not something that BCP does. In other words, this is just an example of the incompleteness of BCP [1].

[1] Sofia Ananieva. Explaining Defects and Identifying Dependencies in Interrelated Feature
Models. Master’s thesis, Technische Universität Braunschweig, Sept. 2016.

**Comment by Subaro** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/6231523/25437288/239947de-2a96-11e7-8b05-3d11034277e6.PNG)
