### ISSUE TITLE
Dimacs Import Stackoverflow Exception

### ISSUE THREAD

**Issue by mnieke** [FeatureIDE/FeatureIDE#566]
#### Prerequisitives
* **Eclipse Version:** 4.7.0
* **FeatureIDE-Version:**  
* **Operating system:** Windows 10 x64
* **Java runtime used to run eclipse:** Java 1.8
* **FeatureIDE Composer:** none
* **Git branch/Commit-ID:**  develop branch, commit: e362093
* **Java compiler used to build the FeatureIDE plugin**:

### Issue description
I try to import the attached dimacs model using the UI in FeatureIDE:
right click -> FeatureIDE -> import from dimacs
Then , I receive a StackOverflowException (see exception.log).

It would be great if anyone could help me with that issue.

[dimacs.zip](https://github.com/FeatureIDE/FeatureIDE/files/1215483/dimacs.zip)

**Comment by tthuem** [comment]
@Subaro @Kogoro This issue is pretty urgent for us. Please prioritize it over all other issues of FeatureIDE (but not over your exams). When will you have time to investigate it?

**Comment by Kogoro** [comment]
First of all, for me the exception.log is empty but I tried to load the file and received a NullPointerException. It seems that the 19th constraint is wrong encoded in the original file or the reading process does not read the constraint correctly. As result, the save process fails for me. I inserted a `if (literal.var == null) return;` after Line 204 in the XmlFeatureModelFormat and now the model to be saved correctly. Because the model is enormous, I deactivated all calculations in the model file by hand. It still delivers now a Java heap space exception from eclipse itself but should load with more heap space. (In my case it seems to need more than 6GB as it still runs very slow).

Note: As this is a workaround, we should take a look whether this is the best solution for the problem. The problem can lay also in other components.

**Comment by mnieke** [comment]
That's strangs. I still receive a StackOverflowException. On two different PCs, eclipse Oxygen and Neon. Both with the current develop branch.
I attached the correct log again.
In the mean time, could you please send the imported model to me?
Thank you!

[log.txt](https://github.com/FeatureIDE/FeatureIDE/files/1217184/log.txt)

**Comment by Kogoro** [comment]
Okay it seems that @TimoGuenther should also have a look at this. The try in line 273 has no catch clauses and the https://github.com/FeatureIDE/FeatureIDE/blob/e362093ea9b052e56964d38b8c0ea12ab9ebc7d6/plugins/de.ovgu.featureide.fm.core/src/org/prop4j/transform/DimacsReader.java file could also be the point for the null pointer explained above.
The model is attached.
[model.zip](https://github.com/FeatureIDE/FeatureIDE/files/1217350/model.zip)

**Comment by TimoGuenther** [comment]
I fixed the stack overflow in https://github.com/FeatureIDE/FeatureIDE/commit/d10b251b6a80ca0168f16702ed7248062a77b583 (see my comment there for implementation details). This fixes the stack overflow, but I personally still get an exception for not having enough memory (results may vary).

@Kogoro: That try statement has no explicit catch block because it is a [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) block. Its only purpose is to [finally](https://docs.oracle.com/javase/tutorial/essential/exceptions/finally.html) close the `Scanner`.

**Comment by mnieke** [comment]
Thank you!
Now it works (with an average memory consumption between 8GB and 9GB ;) ).
To generate product using this feature model I had to increase the timeout of the sat4j solver, otherwise it would interrupt any computations.
