### ISSUE TITLE
Disable Analyzer when analysis is disabled

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#574]
#### Prerequisitives
* **Git branch/Commit-ID:**  `develop`

### Issue description
There are several places of the analyzer which not check if the analysis is enabled. This could be lead to an enormous problem for large feature models. One problem is the calculation of a CNF for constraints even if the analysis is disabled.
Some places that maybe lead to performance issues:
https://github.com/FeatureIDE/FeatureIDE/blob/12c40836f7b960ca1feed8696d1a5797340d3779/plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/editors/FeatureDiagramEditor.java#L882-L905
https://github.com/FeatureIDE/FeatureIDE/blob/94f6b5b262dcb75a8a26b667f5ea48b26d6ad5c4/plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/editors/featuremodel/figures/LegendFigure.java#L202-L211
https://github.com/FeatureIDE/FeatureIDE/blob/94f6b5b262dcb75a8a26b667f5ea48b26d6ad5c4/plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/editors/featuremodel/figures/FeatureFigure.java#L179-L182

All places should be checked for performance improvements. If someone knows also places with analyzer calls, please post or check them also.

**Comment by tthuem** [comment]
@TimoGuenther Do your commits have any performance impact on the creation of the CNF? In the last version we could open large models which we are no longer able to open anymore. This issue is about deactivation at all, but this could require larger refactorings. Hence, the question is whether the CNF creation consumes more resources now and whether we can change this more easily.

**Comment by tthuem** [comment]
Related to #544 and #449

**Comment by TimoGuenther** [comment]
I measured the performance of `AdvancedNodeCreator#createFormula(IMonitor)` with vs. without trace models (using stopwatch tests with 10,000 iterations each). My findings are that the impact of recording trace models while transforming feature models to CNF increases with the feature model size. In a big feature model, trace model generation can easily double the time it takes to generate the CNF.

Because of that, generating trace models is made optional and disabled by default as of https://github.com/FeatureIDE/FeatureIDE/commit/a3b3e2f6e8f1c6b991ca130763202a448d174af1.

**Comment by tthuem** [comment]
How can users enable tracing? Is there a persistent option?

**Comment by TimoGuenther** [comment]
It's not a user setting because the trace model is an implementation detail of no relevance to users. Tracing happens per instance of `AdvancedNodeCreator`. Each client may opt-in on tracing when generating the CNF it wants from its `AdvancedNodeCreator`. Currently, the only client that does that is the explanations backend.

**Comment by Kogoro** [comment]
This method is only called by the AnalyzeVelvetHandler. Maybe we should refactor this into this action. Any reasons to keep it in the plugin class?
https://github.com/FeatureIDE/FeatureIDE/blob/c573e291c761d73ecd0d144cf51236405e822500/plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/FMCorePlugin.java#L147-L233

**Comment by Kogoro** [comment]
@PaulWestphal and @Subaro can you also check if all things are working correctly?

**Comment by PaulWestphal** [comment]
I haven't found any unexpected behaviour.

**Comment by Subaro** [comment]
@Kogoro Seems to work.
