### ISSUE TITLE
Void feature model has no legend entry and root feature is not colored

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#608]
After selecting several features and the constraints and nothing repeatedly, both has disappeared.

![void](https://user-images.githubusercontent.com/5330357/30926333-08732374-a3b5-11e7-8ec7-f37529502be9.PNG)

@TimoGuenther Is that related to your explanations?

**Comment by TimoGuenther** [comment]
These are actually two separate issues. The first is the legend entry for void feature models not appearing. This was a conscious decision in  https://github.com/FeatureIDE/FeatureIDE/commit/1d91580097edc3eb6f267e9eed9d27e4588e611e. I do not know what the reasoning back then was, but that change should probably be undone.

The second issue is the wrong background color of certain features. This is not related to explanations. The activation of an explanation only hides the symptom because it causes a refresh of the involved feature figures.

The issue is with this code inside `FeatureFigure#getToolTip()` introduced in https://github.com/FeatureIDE/FeatureIDE/commit/edb173bc5c79ac88d72b5249eb9975775a46c0f9:
https://github.com/FeatureIDE/FeatureIDE/blob/edb173bc5c79ac88d72b5249eb9975775a46c0f9/plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/editors/featuremodel/figures/FeatureFigure.java#L216-L224

Because of that, hovering over the feature suddenly changes its background color if it has no custom color and is abstract. But why does generating the tooltip even change the background color? And why would the feature color be relevant to the tooltip?

Pretty sure that is not intended behavior, so it is changed as of https://github.com/FeatureIDE/FeatureIDE/commit/04395a2ec2d0a26c14cefaa847954508722b90ef.

**Comment by tthuem** [comment]
Thanks for the first part of the fix. Indeed, I think that https://github.com/FeatureIDE/FeatureIDE/commit/1d91580097edc3eb6f267e9eed9d27e4588e611e should be undone, as it is useful if there are no selection (e.g., when exporting a void feature model to PDF or PNG).

**Comment by Subaro** [comment]
The legend entry is implemented as of #634

They removed the coloring depending on defects and added problem marker for each defect directly to the feature.

**Comment by Subaro** [comment]
@tthuem Should i still push the old void legend entry for the hotfix release?

**Comment by tthuem** [comment]
@Subaro Yes, only the notation should change by their commit.

**Comment by Subaro** [comment]
The old entry is added again now
