### ISSUE TITLE
Feature Request : UUID for each feature

### ISSUE THREAD

**Issue by sjames** [FeatureIDE/FeatureIDE#655]
#### Prerequisitives

* **FeatureIDE-Version: 3.5

### Issue description
Create a UUID for each new feature. The UUID can be used to track the feature along any additional changes in its lifetime - renaming for example.  This UUID can also be used as an identifier for any other tools that may be written.

If a feature is copied from one model to another, the user can be provided with options of using the source UUID or creating a new UUID.

**Comment by tthuem** [comment]
That's a quite intense change, whose benefit is questionable for many parts of FeatureIDE. While feature IDs are certainly a good idea and could be used in feature models and configurations, features are often only referenced by their names. For example, preprocessors use feature names instead of IDs and names are also used in any other composer.

There is already support for renaming. That is, a feature is renamed in all artifacts consistently (except for some minor bugs). Hence, I do not see a need for this heavyweight change. Please give further details, if you still think this would be good to change.
