### ISSUE TITLE
Collapse all is not working

### ISSUE THREAD

**Issue by mnieke** [FeatureIDE/FeatureIDE#697]
#### Prerequisitives
* **Eclipse Version:**  Oxygen 4.7.0
* **FeatureIDE-Version:**  see Git branch / commit ID (seems to be release 3.4)
* **Operating system:** Windows
* **Java runtime used to run eclipse:** Java 1.8
* **FeatureIDE Composer:** none
* **Git branch/Commit-ID:**  develop, 4b6a634
* **Java compiler used to build the FeatureIDE plugin:**

### Issue description
Scenario:
Create a new feature modeling project.
Default generated feature model.
Right-click on the background -> collapse all -> nothing is happening (but dirty flag is set).
Collapsing the root feature manually is working.

**Comment by tthuem** [comment]
Thanks for your issue.

Collapse all is supposed to not collapse the children below the root, because only showing the root feature is typically rather useless. As you are dealing with feature models imported from Dimacs, this is a very special case in which this could make sense to also collapse subfeatures of the root feature.

We could forbid manual folding of the root feature to make it consistent. However, for these degenerated models in which all features are below the root feature, it seems to be rather helpful that you can collapse those features.

Hence, I do not see any action item for the implementation. Please comment on this issue, if you have any thoughts on how to improve the behavior or make it more intuitive.
