### ISSUE TITLE
Simplified creation and handling of extended feature models

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#713]
There are some suggestions to improve the handling of extended feature models.

1. The feature attributes view should be part of the FeatureIDE perspective. It might be necessary to create an extension point to add further views to the FeatureIDE perspective in other plug-ins. Nevertheless, attributes should still work without FeatureIDE being installed, if possible.
2. Once the attribute view is opened and a standard FeatureIDE feature model or configuration is shown, it should be possible to convert it into an extended feature model or extended configuration, respectively. Ideally, by a dedicated button inside of the attribute view.
3. If an extended feature model or configuration is opened and the attribute view is not open, it should be opened automatically. There is a similar handling if an aspect is opened in AspectJ Development Tools.

**Comment by bjthehun** [comment]
Part 3 of this issue seems unclear at the moment. Should the Attribute view be opened every time we open an extended feature model or configuration and it is not open, like it is done in Commit df86755, or should the user be asked first if they want to open that view and be able to configure the opening behavior, like the AspectJ and Constraint View do?

**Comment by SundermannC** [comment]
We discussed this and decided that the Feature attributes view can be opened without asking the user as the attributes view is without alternative to edit attributes and does not change how the feature model editor behaves.
