### ISSUE TITLE
Feature model attributes: work to do

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#777]
1. Selecting/unselecting a feature in the extended configuration should not collapse all tree elements for the FMOutline.
2. FMOutline should not show feature model attributes when only the normal configuration is open.
3. FMOutline shows the wrong message when opening the Source tab of the configuration editor.
4. Attributes view has a strange background color.

**Comment by tthuem** [comment]
5. Attributes view should only be enabled if an extended configuration (or feature model) is opened.

**Comment by Subaro** [comment]
6. Constraints over attributes

**Comment by Subaro** [comment]
7. String Attribute können mit < > <= >= überprüft werden aber es gibt kein „enthält”
8. Beim Slicen entstehen neue constraints, die eine Implikation auf die Wurzel enthalten. Das sind aber redundante Constraints und somit scheint das ein Bug beim Slicen zu sein.
(9. Zählen von Konfigurationen geht nicht. Für ein Modell mit 2 Konfigurationen rechnet er ewig. Nach 5 Sekunden sagt er es wären über 5000 Konfigurationen)
10. Tooltip: Attributes/Inherited Attributes nicht rausschreiben, wenn es gar keine gibt

**Comment by tthuem** [comment]
@Subaro Please translate into English.

**Comment by cpwnd** [comment]
Because this thread seems appropriate, I want to ask if it worth looking into this.

When creating or changing feature attributes within the feature attribute view, every time a change of a field is made (e.g. attribute name, attribute value), the view refreshes its contents and therefore is blocked for further interaction. It surely depends on the model and the machine, but when using models with a decent size (>800 features) it takes >10s on my machine (i5 6300 2,4GHz, 8gb ram).

Maybe the view could only be refreshed/validated, when the model is saved. So a user can make all inputs without a blocked view and when finshed save the model file and trigger the validation. 

However I don't think this is in any sense urgent (at least for me), but I guess this can be done with in the course of the changes mentioned above.

**Comment by tthuem** [comment]
@cpwnd Please create a separate issue for the performance. I can confirm that it takes considerable time to edit extended feature models if the attributes view is open.

**Comment by Subaro** [comment]
Recap and Overview:

Work for release and develop:
- Do not show 'Attributes/Inherited Attributes' in the tooltip if there are no attributes attached to the feature.
- The feature "Sync feature attribute view to selection" should be active by default.

Work for smt solver branch:
 - Selecting/unselecting a feature in the extended configuration should not collapse all tree elements for the FMOutline.
- FMOutline should not show feature model attributes when only the normal configuration is open.
- FMOutline shows the wrong message when opening the Source tab of the configuration editor.
- Attributes view has a strange background color.

For Both:
- Constraints over attributes
