### ISSUE TITLE
Team 2 "Hot Keys and Layouting" (Team Project in Braunschweig 2018)

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#811]
Tentative tasks for Team 2 "Hot Keys and Layouting"

* Add function & hot key for adding a sibling in the feature model. #706
* New extension point to let other plug-ins add actions in feature diagram #366
* Unintuitive behaviour when moving between features using the arrow keys in left-aligned layout. #763
* Unintuitive behaviour when moving between constraints using the arrow keys in left-aligned and left-to-right layout. #765
* Positioning of new features in manual layout #613
* Left-to-right layouts should use larger circles for alternatives and or groups to be better visible #187
* Vectorized graphics instead of bitmap icons in feature diagrams #717

Related tasks

* Removal of features by means of slicing #200
* New dialog when importing feature models in Dimacs format to let users choose whether slicing is applied or not #694

**Comment by tthuem** [comment]
This project will be implemented by Christian Orsinger and Sabrina Hugo

**Comment by tthuem** [comment]
New tasks raised by Paul:
* Selection of feature including subtree in Feature Model editor #820

**Comment by tthuem** [comment]
Screencast is available online https://youtu.be/hiYGg5Tij5k

**Comment by tthuem** [comment]
We should consider whether we want to remove the menu entry to delete a feature including its subtree, as this can be done by first selecting the subtree and then deleting all selected features. What do you think?

**Comment by BassMonster** [comment]
I think this feature is a comfort feature. The user can delete the whole subtree with just one click, otherwise it would take to clicks. The way you describe offers other possibilities like delete the big part of a subtree by deselecting all features that should not be removed. That is why I think the menue entry should stay.

**Comment by PaulWestphal** [comment]
These issues remain open:

- New extension point to let other plug-ins add actions in feature diagram #366
- Left-to-right layouts should use larger circles for alternatives and or groups to be better visible #187
- Vectorized graphics instead of bitmap icons in feature diagrams #717
- Removal of features by means of slicing #200
- New dialog when importing feature models in Dimacs format to let users choose whether slicing is applied or not #694

Also, the new Create Sibling and Select Subtree actions do not have hotkeys yet.

**Comment by PaulWestphal** [comment]
I've added the missing hotkeys, fixed compatibility with the new layouts and merged the team 2 branch into develop.

**Comment by tthuem** [comment]
@PaulWestphal If this is done, please close this issue and all others that have been implemented.

**Comment by tthuem** [comment]
@PaulWestphal The action to delete a feature including its subfeatures was supposed to be removed once we have a selection of a subtree. It can be done in two steps now by first selecting the subtree and then deleting all selected features. Please remove the action from the menu and all code accordingly.

![image](https://user-images.githubusercontent.com/5330357/54916980-0fc77b00-4efb-11e9-9220-39d8f716ba8b.png)

**Comment by PaulWestphal** [comment]
bf6561ba76d754c6b0493795c762596553e3950b
