### ISSUE TITLE
FeatureIDE Dimacs Importer Or Expression with One Child

### ISSUE THREAD

**Issue by mnieke** [FeatureIDE/FeatureIDE#865]
### Issue description
There seems to be an issue in the Dimacs importer of FeatureIDE.
My collegue used the KConfigReader to extract Dimacs models of the Linux Kernel.
Then he imported this model to FeatureIDE.
However, in the cross-tree constraints there seems to be an issue with "Or" clauses (at least one).
There are nodes of the type "Or" that have only one child node.
Semantically, this is not a problem.
But such constraints could be more compact and at least the DeltaEcore and DarwinSPL feature-model importers expect(ed) two children of "Or" nodes (as "Or" is a binary expression and should(?) have two children).

The concrete models can be found here (caution: _very_ large models):
[https://github.com/PettTo/Feature-Model-History-of-Linux](url)
The issue appeared in the model of the 2018-01-12T00_14_28+01_00, and the "Or" constraint has one child "-BFIN_MAC_USE_HWSTAMP"

**Comment by skrieter** [comment]
Hi @mnieke,
This is intended behavior of the importer. In order to traverse CNFs more easily, we wanted to have a sort of regular structure of the propositional nodes when in CNF. Hence, they should always have the form of an And node that has only children consisting of Or nodes, which only have children consisting of literal nodes. This avoid unnecessary check with instanceof and cleans up the code quite a bit.

However, there is a simple fix for your problem. When you problematically load a model from a file, just call the method flatten() on the resulting And node and you get the more compact structure you desire. I fixed the default behavior for importing a feature model via the FeautreIDE GUI. The flatten method is now called automatically for importing a model from DIMACS.
