### ISSUE TITLE
GUI Test EditedCollapsedAttributesInFeatureDiagram verification fails on travis. 

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#895]
https://travis-ci.org/FeatureIDE/FeatureIDE/builds/577889013#L4281

It just says the following:

> [INFO] Fail 12 (13) processed. 2 failed. spent: 4:42, 0:00 mins remaining. SetCollapsedInFeatureDiagram. time: 6020ms  Cause: Widget text verification 'EditedCollapsedAttributesInFeatureDiagram' failed:

There is no additional information indicating why it failed. The test runs successfully every time for me locally.

**Comment by tthuem** [comment]
@PaulWestphal Can you disable the GUI test temporarily for the release 3.6.0?

**Comment by PaulWestphal** [comment]
Done.

**Comment by tthuem** [comment]
Due to a change in the example, the widget text for HandsOn2 needs to be updated also. I was not able to change the text easily, as it requires a special Eclipse installation. One the text is updated in the GUI test verification, the verification needs to be included again: https://github.com/FeatureIDE/FeatureIDE/commit/b24b9eed74d6c31fa1b90d2e6ea7cea1cf6999c0

**Comment by PaulWestphal** [comment]
fixed f0ca73c19949b3acc9e3458e9a4ea3a9ec86ed62

handson2 verification is updated, also.
