### ISSUE TITLE
Opening a void feature model for the first time leads to an update problem

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#897]
#### Prerequisitives
* **Eclipse Version:**  2019-03
* **FeatureIDE-Version:**  3.6.0
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** Java 8 Update 201
* **Git branch/Commit-ID:** release 3.6 https://github.com/FeatureIDE/FeatureIDE/commit/04eb097507f6b1634133fd44b6ce3ed7b78c0195

### Issue description
Imported Elevator-Antenna-v1.0 and opened the feature model:

![image](https://user-images.githubusercontent.com/5330357/64017691-8b70c800-cb2a-11e9-8952-65d17626bc70.png)

Problem occurs only when opened the first time. Can be reproduced also after closing and reopening the project. Seems to be a simple update problem with the void property.

**Comment by Subaro** [comment]
The layout problem always happens when the feature model is opened for the first time. The same issue appears with any defect (not only void) as shown below:

![grafik](https://user-images.githubusercontent.com/6231523/64607340-dbb41980-d3b7-11e9-99de-cdb85f0a58ca.png)

Generally is a layout call missing after analyzing the feature model.
