### ISSUE TITLE
Runtime Config: Configuration file "runtime.properties" is not created

### ISSUE THREAD

**Issue by gusschwto** [FeatureIDE/FeatureIDE#902]
#### Prerequisitives
* **Eclipse Version:**  2019-06 (4.12.0)
* **FeatureIDE-Version:**  3.6.0.201908302227
* **Operating system:** Microsoft Windows 10 Home Version 1903 Build 18362.295
* **Java runtime used to run eclipse:** jdk-12.0.2
* **FeatureIDE Composer:** n.a.
* **Git branch/Commit-ID:**  n.a.
* **Java compiler used to build the FeatureIDE plugin:** n.a.

### Issue description
After creating a new FeatureIDE project, based in Runtime Configuration, **no** "runtime.properties" file is created in project directory. Also updating the model.xml and configs/default.xml does not cause a creation of "runtime.properties".

For testing purpose I created a kind of ~"hello world" implementation to cause content in the bin-folder. Also here is no "runtime.properties" added - As described in feedback to issue #894 "Runtime Parameters: Generation of runtime.properties into different folder" (-> Most likely linked to general non-creation.)

**Hint:**
In one of my trial FeatureIDE-projects a "runtime.properties" was created. Reason unclear.

**Comment by Subaro** [comment]
@gusschwto 
There are two different approaches for runtime configurations supported by FeatureIDE. You can switch between both approaches. For this you have to right click on the project > Properties > FeatureIDE > Feature Project > Composition Mechanism. 

Set the mechansim to `Parameters` to use a `runtime.properties` file containing the features which are currently selected/deselected. These parameters can be read at runtime and used to create variable applications. The `runtime.properties` should be generated when changing the current configuration or setting the current configuration of the project.

When using the Composition Mechanism `Run Configurations` no `runtime.properties` is generated because `Run Configurations` does not require a file containg all selected/unselected feature. Instead you pass the selected feature as parameters to the java project. 

If you used the `Parameters` project make sure you set a current configuration. The `runtime.properties` is generated with the help of a currently selected configuration, therefore, if no current configuration is set then no file is generated. To mark a configuration as current, right-click on any configuration > FeatureIDE > Set as current configuration. After that try to change the current configuration or model and a respective `runtime.properties` file should be generated.

**Comment by tthuem** [comment]
@gusschwto You may also want to have a look at the according examples: HelloWorld-RuntimeParameters and HelloWorld-RuntimeProperties. Please let us know if you still have any problems. For now, we are closing the issue.
